# DO NOT CHANGE
configVersion: ${project.version}

# Backup time (0 - 23)
backupTime: 0
# Backup period in hours
backupPeriod: 24
# What to do after backup, (STOP, RESTART, NOTHING)
afterBackup: NOTHING
# Max backups in backups folder, 0 to make in unlimited
maxBackupsNumber: 7
# Max backups folder weight in MB, 0 to make it unlimited
maxBackupsWeight: 0
# Should backups be packaged in a zip archive
zipArchive: true