# DO NOT CHANGE
configVersion: 6.0
lastBackup: 0
lastChange: 0


# (true/false) Automatic backup once in a specified period
autoBackup: true

# (Path) Full directory where backups will be stored
backupsFolder: plugins/Backuper/Backups

# (0 - 23). Backups will be made at this time every day. (backupPeriod will be automatically set to 24 hours). -1 to disable backup time fixation
backupTime: -1
# (MINUTES > 0 or -1) Backup period. To change this value you need to set backupTime to -1
backupPeriod: 1440
# (STOP, RESTART, NOTHING) What to do after backup
afterBackup: NOTHING

# (true/false) The backup will only occur if the world has been changed since the last backup. If the world has not been changed, this backup cycle will be skipped
skipDuplicateBackup: true
# (>= 0) Max backups in backups folder, 0 to make it unlimited
maxBackupsNumber: 0
# (MB >= 0) Max backups folder weight, 0 to make it unlimited
maxBackupsWeight: 0
# (true/false) Should backups be packaged in a zip archive
zipArchive: true

# (SECONDS < backupPeriod * 60) A notification about server restart will be sent to all players on the server {timeToAlertBeforeRestart} seconds before the restart (if afterBackup = NOTHING, no notification will be sent). -1 to disable notifications
alertTimeBeforeRestart: 60

# (true/false) Better logging (Some statistic and other information for debugging, you probably don't need it)
betterLogging: false